### ISSUE TITLE
Add hastag + position de la miniature

### ISSUE THREAD

**Issue by Devstored** [wkaisertexas/tiktok-uploader#1]
Hello, I love your library it works perfectly and meets my needs! I would like to know if you could add an option to manage Hashtags. Because currently it doesn't work if I insert #test at the end of the description.

Also, I don't know if it's possible to change the thumbnail by moving the slider to X sec of the video?

Thank you so much !

**Comment by wkaisertexas** [comment]
# Hashtags and Mentions
Sure. Hashtags and mentions are a little harder to automate because they are created through are more convoluted process. The HTML they generate is fairly simple, however. 
 
<img width="503" alt="Screenshot 2023-02-28 at 1 09 39 PM" src="https://user-images.githubusercontent.com/27795014/221943118-b5420649-902c-4a09-8ac3-271675a20172.png">
<img width="1012" alt="Screenshot 2023-02-28 at 1 10 27 PM" src="https://user-images.githubusercontent.com/27795014/221943197-c1618bac-ad0d-4a4e-9bee-42bfd7f37855.png">

Developing this system is definitely something I will do, but I have to think about how to make it resilient enough to not break when TikTok updates their site.

--- 
# Setting Thumbnails
Settings thumbnails was also something I did not envision, but it requires similar lower-level manipulation.

Do you have a specific part of the video you want to thumbnail to be, or would you more so be randomly the thumbnail frame?

---
# Custom Functions
Something I will 100% do in the next release is allow the user to pass a custom function which is passed the webdriver before submitted. This way, the user can make any custom actions they like.

**Comment by Devstored** [comment]
@wkaisertexas  Regarding Hashtags, I have inserted this piece of code in your library. I fill in a list as a parameter and it works pretty well but really not robust in my opinion.

`    if hashtag:
        time.sleep(300)
        for unit_hashtag in hashtag:
            time.sleep(2)
            desc.send_keys(" ")
            desc.send_keys(str(unit_hashtag))
            time.sleep(2)
            desc.send_keys(Keys.RETURN)`



Regarding the thumbnail, for example I would like the bot to select 3 seconds from the video.

Also, do you know how long cookies are valid?

Thank you so much

**Comment by wkaisertexas** [comment]
Version 0.1.2 adds support for hashtags and mentions. Thanks for the suggestion. 

Changing the thumbnail was not tackled as to set the video's position to 3 seconds in, you would also need to know the length of the video, potentially requiring more libraries and in general I think it may be too broad for the scope of this library. 

I really intended this library be used as the final step of a video uploading pipeline. In that pipeline, the first segment of the video is designed to function as a thumbnail.

Check out [@c_span](http://tiktok.com/@c_span). For these videos, the first 10 seconds have a number which represents which part of the series the video is in.
