### ISSUE TITLE
Code dont work

### ISSUE THREAD

**Issue by leonardkrief** [wkaisertexas/tiktok-uploader#11]
Bug happening at line 269 of upload.py:
```
# NOTE (IMPORTANT): implicit wait as video should already be uploaded if not failed
# An exception throw here means the video failed to upload an a retry is needed
WebDriverWait(driver, config['implicit_wait']).until(upload_confirmation)
```
I managed to fix it but it wasnt that simple. Code simply dont work, i dont know why it got stars lol

**Comment by wkaisertexas** [comment]
Hell, I am sorry this was not working for you.

This check is supposed to catch when TikTok will sometimes not allow the initial upload of your video sometimes (there is a retry parameter).  TikTok not allowing your video to be uploaded in my experience is most commonly the result of too many requests in a short period of time.

> During development, I found that waiting a few hours was enough to get TikTok to stop rejecting the upload.

---

If I may ask, what change did you make to fix this issue that you have been having?

**Comment by leonardkrief** [comment]
I managed to simplify the changes I made. I forked your directory and made the changes, you can check it on my profile
Basically 2 things:
1) your 'loading indicator' was the word 'Cancel' in the HTML but this word might never appear on other languages browsers, so I changed it to data-pct element which is not language dependent
2) you wasn't waiting for the 'loading logo' to disappear so I added this. This comment do not seem relevant anymore so I removed it
````
# NOTE (IMPORTANT): implicit wait as video should already be uploaded if not failed
# An exception throw here means the video failed to upload an a retry is needed

**Comment by wkaisertexas** [comment]
Being language-dependent is definitely my bad here. 

The comment is still useful. I probably just need to rephrase it. 

The prior check basically made sure the video was no longer uploading. If that is the case and the video is not found, then that means that the upload fails. 

Because people's internet connections are all different, the `explicit wait` as defined in the `config.toml` is quite large. However, most of the time, the video would fail to upload quite quickly.

So, to give people plenty of time to upload their videos while not having them wait if the video fails, this two-step system is required.

**Comment by leonardkrief** [comment]
Yes, I think putting it to 60secs is good as you did. On my machine, selenium-driven browser is really slow and vid takes up to 30secs to fully upload from the moment the set_video function is called.

And if I might ask, why did you add a tiktok_uploader directory in your src ? I think this is confusing. Plus it has the same name as the repo which is also confusing. If there is no specific reason for this, you could delete the src/tiktok_uploader directory and move its content to src

**Comment by wkaisertexas** [comment]
So, naming the directory `tiktok_uploader` was required because of the fact that this package is published on *PyPI*. I technically had two options of how to do it (`src/tiktok_uploader` or `tiktok_uploader`) . I opted for the former because the `src` paradigm is a little bit more understandable to programmers used to other languages in my opinion.

I am working on a release which logs each intermediate set and adds support for headless browsers, but it is finals at my university, so it will have to be after that.
