### ISSUE TITLE
The result is failed even when it works and publish on tiktok, why?

### ISSUE THREAD

**Issue by felipexpert** [wkaisertexas/tiktok-uploader#121]
The result is failed even when it works and publish on tiktok, why?

**Comment by callum-fortune** [comment]
I believe this is because the code raises an `FailedToUpload(exception)` which should be in an exception block. I have addressed this issue in my PR (https://github.com/wkaisertexas/tiktok-uploader/pull/125).

Since adding this change, I can see the terminal output that it is uploaded successfully and the selenium instance is closed correctly.

**Comment by wkaisertexas** [comment]
Thanks @callum-fortune
