### ISSUE TITLE
Add playlist and run copyright check

### ISSUE THREAD

**Issue by pongo9** [wkaisertexas/tiktok-uploader#13]
Add playlist and run copyright check

**Comment by wkaisertexas** [comment]
I don't think adding to playlist is something that is feasible for this project to support. The ability to place videos in a playlist is only available to those with over a thousand subscribers. I do not even have the capacity to test this right now.

As for copyright checks, this could be something added into the future. However, it would add additional complexity because whether or not an upload failed due to a copyright check or the page not loading correctly would be harder to communicate in documentation.

That copyright check in my opinion is mostly a postural where they are trying to claim they are trying harder to combat copyrighted material being used on their platform. My advice would be that you likely know whether or not you are uploading copyrighted material anyways.
