### ISSUE TITLE
 Error when running script with my cookies

### ISSUE THREAD

**Issue by TheOverflowProgrammer** [wkaisertexas/tiktok-uploader#134]
Good afternoon everyone, I encountered the following problem: when I try to run a script with my cookies, which I made myself, I get this error:
tiktok_uploader.auth.InsufficientAuth:
    Insufficient authentication:

    > TikTok uses cookies to keep track of the user's authentication or session.

    Either:
        - Use a cookies file passed as the `cookies` argument
            - easily obtained using https://github.com/kairi003/Get-cookies.txt-LOCALLY
        - Use a cookies list passed as the `cookies_list` argument
            - can be obtained from your browser's developer tools under storage -> cookies
            - only the `sessionid` cookie is required
Please help me solve my problem

**Comment by TheOverflowProgrammer** [comment]
I solved the problem by removing the \t argument from the split() function of the get_cookies() method in the AuthBackend class

**Comment by Jamadoo** [comment]
@TheOverflowProgrammer This script uses the Netscape cookie format for its cookies. Consider using [cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) to get your cookies file if any issue persists.

How to use the extension:
1) Add the extension to your browser
2) Go to tikrok.com and log in
3) Click the extension 
4) Click export as
5) Choose a location to save the cookie file

You can then pass your cookie file in this uploader

If your issue is resolved, please close the issue
