### ISSUE TITLE
Is it possible to make a version with an interface.

### ISSUE THREAD

**Issue by xingheyiyi** [wkaisertexas/tiktok-uploader#41]
Is it possible to make a version with an interface.

**Comment by wkaisertexas** [comment]
You mean like TikTok.com?

This project was mostly built as a way to schedule upload projects I built. Now that they added that feature, this project is near mute. 

Making an interface is a decent amount of work and not something I am considering (especially since hosting costs could be problematic and the like)

**Comment by xingheyiyi** [comment]
The cookie keeps failing, can you help me see what's wrong?
