### ISSUE TITLE
Incorrect redirection

### ISSUE THREAD

**Issue by userKyamao** [wkaisertexas/tiktok-uploader#46]
Hello, I have a problem with my script at step [22:23:18] Navigating to upload page, my browser goes to the content creator page for payment (https://www.tiktok.com/creator-center/ineligible), is this normal because I'm in France?

**Comment by wkaisertexas** [comment]
Yes, the creator center is being rolled out at different rates in different parts of the globe. 

Because of the users of the library are in the United States, I switched the `upload` key in the `config.toml` to be the creator center.

I would [install the library from source](https://github.com/wkaisertexas/tiktok-uploader#building-from-source) so that you can readily modify the `config.toml` to fit your localization needs.
