### ISSUE TITLE
Schedule tiktok Uploads

### ISSUE THREAD

**Issue by tidusete** [wkaisertexas/tiktok-uploader#5]
Good afternoon,
I would like to know if you could implement a feature that allows you to upload videos to tiktok using the scheduler that tiktok offers when you use business accounts.
The idea I have in mind is to run the script once a week and have the script schedule the upload of all videos to tiktok.
Is this possible?

**Comment by wkaisertexas** [comment]
Technically, yes. I have not played around with business accounts so I am not quite familiar. I currently have two accounts uploading videos which just use a `cron` job to schedule everything at the correct time. 

If you are going to automate the uploading anyways, why couldn't you just run the script more often instead of just once a week. Having the script randomly popup on your computer can be a little annoying, but much preferably imo. 

> TikTok is providing this feature natively through a closed Beta at this time. Using TikTok's official solution if you have a business account is likely better in the end.

[https://ads.tiktok.com/marketing_api/docs?id=1737587322856449](Upload a video to TikTok using the Business API)
[https://ads.tiktok.com/marketing_api/docs?id=1737565048641538](Publishing a video to TikTok using the Business API)

This may be a feature I add eventually, but not at the moment just due to time constraints.

**Comment by tidusete** [comment]
I'm completly agree with your idea and ideally I started to implement it with my raspberrypi 4, but I was wasted and I decided to go to the most standar way.
Said that, I have the following problems:
I don't have a server that can be running 24/7
I just have 1 account that I would like to test.
So my idea was to try to go to serverless with a powerful computer

May I ask which setup do you have to run it?

Thanks @wkaisertexas for your time

**Comment by wkaisertexas** [comment]
My solution is not ideal, but I am currently just using a background process on my Desktop PC. Implementation on the Raspberry PI should not be too difficult as it only requires a custom webdriver which can be tricky. 

[Getting a Selenium WebDriver on Raspberry PI](https://patrikmojzis.medium.com/how-to-run-selenium-using-python-on-raspberry-pi-d3fe058f011)

Once created, this can be passed as a custom `browser_agent` to either `upload_video` or `upload_videos`.
